#!/bin/sh

# These are needed by GCC
ARCH="arm"
ABI="gnueabi"
CTARGET="${ARCH}-unknown-linux-${ABI}"
export ARCH ABI CTARGET

MAKEOPTS="-j 3"
CFLAGS="-O2 -pipe"
CXXFLAGS="${CXXFLAGS}"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"

export CFLAGS CXXFLAGS LDFLAGS MAKEOPTS
