#!/bin/bash

# These are needed by GCC
ARCH="arm"
ABI="gnueabi"
CTARGET="${ARCH}-unknown-linux-${ABI}"
export ARCH ABI CTARGET

MAKEOPTS="-j 3"
CFLAGS="-O2 -pipe"
CXXFLAGS="${CXXFLAGS}"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"

# armv7 specific args
# armhf: --with-fpu=vfpv3-d16
GCC_CONFIGURE_ARGS="--with-arch=armv7-a --with-float=soft"

export CFLAGS CXXFLAGS LDFLAGS MAKEOPTS GCC_CONFIGURE_ARGS
