#!/bin/bash

MOLECULE_BIN="/usr/bin/molecule"
if [ ! -x "${MOLECULE_BIN}" ]; then
    MOLECULE_BIN="../molecule/molecule.py"
fi

MOLECULE="${MOLECULE:-${MOLECULE_BIN}}"
if [ ! -x "${MOLECULE}" ]; then
    echo "Cannot find molecule at ${MOLECULE}" >&2
    exit 1
fi

UBUILD_LOGGING_CFGFILE="${PWD}/conf/ubuild.logging.conf"
export UBUILD_LOGGING_CFGFILE

MOLECULE_PLUGIN_MODULES="plugin.ubuild_plugin"
export MOLECULE_PLUGIN_MODULES

PYTHONPATH="./:${PYTHONPATH}"
export PYTHONPATH

exec "${MOLECULE}" "${@}"
